services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sisprime-multi-endoscopia-backend
    ports:
      - "8802:8501"
    volumes:
      - ./backend/logs:/app/logs
      - ./backend/outputs:/app/outputs
    restart: unless-stopped
    networks:
      - endoscopia-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sisprime-multi-endoscopia-frontend
    env_file:
      - ./frontend/.env.local
    ports:
      - "8801:3000"
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - endoscopia-network

networks:
  endoscopia-network:
    driver: bridge
